# Generated by Django 3.2.5 on 2021-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtrendsapi', '0002_auto_20210711_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
    ]
