# Generated by Django 3.2.5 on 2021-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtrendsapi', '0003_item_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Success'), (2, 'HTTPError'), (3, 'URLError'), (4, 'Others')], default=0),
        ),
        migrations.AddField(
            model_name='scrape',
            name='status_info',
            field=models.TextField(null=True),
        ),
    ]
